### PR TITLE
Add Fedora instalation instructions

### PR DESCRIPTION
**Pull request by tim77**
Packaged for Fedora and now [on QA](https://bodhi.fedoraproject.org/updates/FEDORA-2019-cbba1c33f3).

### CODE REVIEW

**Comment by PapyElGringo** [comment]
How this package get updates?

**Comment by PapyElGringo** [comment]
I though I had to do a make file or something and can you check this? https://www.reddit.com/r/unixporn/comments/c8le62/gnome_materialshell_beta/eso3gz5?utm_source=share&utm_medium=web2x

**Comment by tim77** [comment]
> How this package get updates? Im pretty newb about packaging stuff

Maintainer pushing new version or git snapshots via Bodhi (update service in Fedora) and users giving positive or negative karma to update if it broken.

> I though I had to do a make file or something and can you check this? https://www.reddit.com/r/unixporn/comments/c8le62/gnome_materialshell_beta/eso3gz5?utm_source=share&utm_medium=web2x

OBS in SUSE nice thing but in is not official repo, it is users repository and quality of packages may vary. Ideally you should write a meson build file. But any maintainer of any distro can write their custom build and install scripts in SPEC file for example. This extension is easy to maintain, but users can benefit of having packaged version. If something broke then they can easily rollback to previous version of package for example.

**Comment by PapyElGringo** [comment]
I guess you didn't pull for a long time ^^

**Comment by tim77** [comment]
I built it from day 1 since you released it. :) But in COPR repos (this like OBS in SUSE)

https://copr.fedorainfracloud.org/coprs/atim/gnome-shell-extension-material-shell/

**Comment by PapyElGringo** [comment]
Well since we are fixing bug almost everyday it's start to be faaaar day 1 ! The readme has been also updated

**Comment by PapyElGringo** [comment]
So to be sure if they uses `sudo dnf install gnome-shell-extension-material-shell` which version will they get? The day one or the current?

**Comment by tim77** [comment]
This snapshot https://github.com/PapyElGringo/material-shell/commit/ac433ba7dbfadc22ee9ae8ce8a8b8cfeb91866b7

You can check it [there](https://github.com/PapyElGringo/material-shell/commit/ac433ba7dbfadc22ee9ae8ce8a8b8cfeb91866b7).

But better do not merge this PR until Bodhi push it into **Stable** repos. You can track the progress [there](https://bodhi.fedoraproject.org/updates/FEDORA-2019-cbba1c33f3).

DeepinScreenshot_select-area_20190718021058

**Comment by PapyElGringo** [comment]
Ok ^^ where can I find the snapshot used? If I want to check later if the package has been updated

**Comment by tim77** [comment]
You can watch source and all commits [there](https://src.fedoraproject.org/rpms/gnome-shell-extension-material-shell) and [there](https://apps.fedoraproject.org/packages/gnome-shell-extension-material-shell) is app version page

**Comment by PapyElGringo** [comment]
Ok perfect ! Thanks you !

**Comment by tim77** [comment]
Finally in **Stable** now. Now this can be merged. And i'll push new update with latest version today... :) 
DeepinScreenshot_select-area_20190726152213

**Pull request merged**
