### PR TITLE
Vertical layout

### PR DESCRIPTION
**Pull request by paradoxxxzero**
Here a simple adaptation of grid layout but with a vertical split first
Screenshot from 2019-07-08 11-25-52

### CODE REVIEW

**Comment by PapyElGringo** [comment]
Before merging this we need to develop the setting screen to set the layouts enabled list

**Comment by PapyElGringo** [comment]
After giving some thought can you just update the grid layout and check the workarea ratio to determine to tile vertically or horizontally?

**Comment by paradoxxxzero** [comment]
I added the settings screen, i'll try to add an auto-grid layout that use the screen ratio.

**Comment by PapyElGringo** [comment]
Move discussion here #51

**Pull request closed without merging**
