### PR TITLE
Added installation instructions to README.md to install from AUR

### PR DESCRIPTION
**Pull request by henri98**
Added installation instructions for installing material-shell in Arch Linux based distributions using the AUR

### CODE REVIEW

**Comment by PapyElGringo** [comment]
Lol check #52 it's serve the same goal and I have the same comment to make

**Comment by PapyElGringo** [comment]
And it's seem that I have to thanks you for this package :+1:

**Comment by henri98** [comment]
Ohhh Hahah, didn't saw pull request #52. Np, if there will be a release a separate package can be made on the release, this will be the more stable version.

**Comment by PapyElGringo** [comment]
Well it's seem that I didn't validated my comment properly earlier ! Could you link to the AUR page instead of giving a command? Seem not everyones are using Yay

**Comment by henri98** [comment]
I will at least add this link: https://aur.archlinux.org/packages/gnome-shell-extension-material-shell-git/

Leave the yay example there? Most users will know yay and be able to translate the command into a command for the AUR helper they are using.

**Pull request merged**
