### PR TITLE
Revamp README and add instructions for compiling Sass

### PR DESCRIPTION
**Pull request by nununoisy**
Just a few edits to improve consistency within the README. I also figured that people who would be editing the Sass might want instructions on compiling it.

### CODE REVIEW

**Comment by PapyElGringo** [comment]
Nice! Could you add a distinction for #62 ?

We also should create a different file for Contributing Instructions and put the sass things and others contributions instructions on it ! To give us more space on the main Readme.

**Comment by nununoisy** [comment]
The reason I added Sass instructions into the README was to simplify the process of changing the shell color. I can move it to CONTRIBUTING.md if need be

**Comment by nununoisy** [comment]
Alright. I fixed the merge conflict and made the requested changes.

**Comment by PapyElGringo** [comment]
Thanks !

**Pull request merged**
